parameters:
    database_driver: pdo_pgsql 
    database_host: ec2-23-21-186-85.compute-1.amazonaws.com
    database_port: 5432
    database_name: d81f7fui1q08qr
    database_user: kkciadhnfmtvkn
    database_password: 5ac4ae1507a6a8a9a0958c6294c9a13e974c7d1bfdc524bfea1dfc49b8b52841
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
