commende_index:
    path:     /commende/list
    defaults: { _controller: "AppBundle:Commende:index"}
    methods:  GET

commende_performances:
    path:     /performances/list
    defaults: { _controller: "AppBundle:Commende:performances"}
    methods:  GET

commendes_list_insident:
    path:     /{insident}/list/insident
    defaults: { _controller: "AppBundle:Commende:listByInsident" }
    methods:  [GET, POST]

commende_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Commende:show" }
    methods:  GET

commende_new:
    path:     /new
    defaults: { _controller: "AppBundle:Commende:new" }
    methods:  [GET, POST]

commende_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Commende:edit" }
    methods:  [GET, POST]

commende_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Commende:delete" }
    methods:  DELETE
