AppBundle\Entity\Souscripteur:
    exclusion_policy: none
    properties:
        id:
            groups: [ligne']
        nom:
            groups: ['ligne']
        prenom:
            groups: ['ligne']   
        contrat:
            groups: ['ligne']   
        mode:
            groups: ['ligne']             