AppBundle\Entity\PointVente:
    exclusion_policy: none
    properties:
        id:
            groups: ['pointvente','commende']
        nom:
            groups: ['pointvente','commende']
        ba1:
            groups: ['pointvente','commende']
        ba2:
            groups: ['pointvente','commende']
        nom:
            groups: ['pointvente','commende']
        type:
            groups: ['pointvente','full']
        nomGerant:
            groups: ['pointvente','full']
        telGerant:
            groups: ['pointvente','full']
        description:
            groups: ['pointvente','full']
        quartier:
            groups: ['pointvente','full']                        

              